DELETE FROM events;
DELETE FROM locations;
DELETE FROM compilation_events;
DELETE FROM comments;

ALTER TABLE events ALTER COLUMN id RESTART WITH 1;
ALTER TABLE locations ALTER COLUMN id RESTART WITH 1;
ALTER TABLE comments ALTER COLUMN id RESTART WITH 1;
TRUNCATE TABLE compilations RESTART IDENTITY CASCADE;